### ISSUE TITLE
[Admin][New Requests] Show Role in the list

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#47]
We should show role instead of phone number

**Comment by MuhammadSarimBader** [comment]
fixed

**Comment by upliftdawah** [comment]
still not showing role on this screen

![33FB88BD-9807-4DEB-83C4-C8C5C96D8F05](https://user-images.githubusercontent.com/61668427/82167572-1b999d80-9871-11ea-9f80-45fd7c0ec111.png)

**Comment by upliftdawah** [comment]
not needed
