### ISSUE TITLE
[Signup] Email verification message

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#5]
Right now the screen that comes after the signup form is submitted has message shown in screenshot below, please change it to:

Heading: "Pending Email Verification"
Text: "A verification email has been sent to "<email address>". Please verify your email and continue using Sign In button.
[Sign In]    [Cancel] <-- buttons (Both buttons should take to login screen, but in case of Sign in click prefill the email address field)
Haven't received email yet? Resend verification email <-- link button

![735E5CB1-5C67-4E39-9702-A1CAE7CDB203](https://user-images.githubusercontent.com/61668427/78104449-1ad1a880-73a4-11ea-90f4-ed05183436ed.png)

**Comment by MuhammadSarimBader** [comment]
Resolved

**Comment by upliftdawah** [comment]
Seems like we are still calling send email verification api. When I currently sign up, it shows this screen [1], which contains the text I provided but the buttons are still the same. Then immediately after that a pop shows up with error[2] and then it goes back to old text[3]. Please remove any email verification api call we are making and fix the button texts as described above. (See screenshots of [1], [2] and [3] below):

[1]
![image1](https://user-images.githubusercontent.com/61668427/82165122-a9bd5600-9868-11ea-856d-f249a7757857.jpeg)

[2]
![image0](https://user-images.githubusercontent.com/61668427/82165112-a32ede80-9868-11ea-9ce2-9c240c3cec2f.png)

[3] 
![image2](https://user-images.githubusercontent.com/61668427/82165134-afb33700-9868-11ea-8775-0aeac8f8ff00.png)

**Comment by upliftdawah** [comment]
verified
